[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 9600
upload_speed = 921600
build_flags =
    -Wall
    -Wextra
    -Wno-unused-parameter
